version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    ports:
      - "5173:5173"
      - "6006:6006"
    volumes:
      - ../app:/usr/src/app:cached
      - /run/host-services/ssh-auth.sock:/ssh-agent #SSHエージェントのソケットをマウント
    environment:
      - SSH_AUTH_SOCK=/ssh-agent # コンテナ内でSSHソケットを利用
    stdin_open: true
    tty: true
